import React, { useState } from 'react';
import JSZip from 'jszip';
import {
  Download,
  FileText,
  Copy,
  Check,
  X,
  Archive,
  Share2,
  ExternalLink,
  HardDrive
} from 'lucide-react';
import { ARCHITECTURE_NODES, RESEARCH_MAPPING_DATA } from '../data/evaluationData';

interface ExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  lang: 'en' | 'ja';
}

export const ExportModal: React.FC<ExportModalProps> = ({ isOpen, onClose, lang }) => {
  const [copiedText, setCopiedText] = useState(false);
  const [copiedUrl, setCopiedUrl] = useState(false);
  const [isZipping, setIsZipping] = useState(false);

  if (!isOpen) return null;

  const appUrl = window.location.origin;

  // Complete Markdown documentation
  const generateMarkdownDoc = () => {
    return `# Universal Filtration & Biomorphic Cosmology
## Grand Unified Provisional Architecture v2.0
*Public Domain Framework & Theory Specification*

---

### 1. 概要 (Executive Summary)
本フレームワークは、現代宇宙論が直面する4大難問（ハッブル・テンション、ダークマター未検出、多世界解釈の質量保存則破綻、熱的死）を、「全一的濾過カスケード（Universal Cascade Filtration）」と「生体膜分裂代謝（Biomorphic Brane Mitosis）」の単一原理によって完全解決した大統一モデルである。

---

### 2. 全8階層アーキテクチャ (The 8-Tier Architecture)
${ARCHITECTURE_NODES
  .map(
    (d) => `#### ${d.japaneseName} (${d.name})
- **役割:** ${d.role}
- **詳細機構:** ${d.description}
- **物理・科学的類似点:** ${d.scientificAnalog}
- **整合性スコア:** ${d.breakthroughScore}%
`
  )
  .join('\n')}

---

### 3. 14大洞察 (The 14 Fundamental Insights)
1. **洞察①：膜張力効果（暗黒エネルギー）** — 宇宙の加速膨張は空間自体の自発膨張ではなく、外側にある11次元緩衝スープとの相互作用による次元膜の張力（抗力）である。
2. **洞察②：特異点の室外機排熱** — 相対論的ジェットはエントロピーゴミを外へ捨てる室外機であり、熱的死を永久に防いでいる。
3. **洞察③：知性のフロンティア開拓** — 生命の知性は宇宙の維持者ではなく、漏洩する定義を捕集し未定義を取り込んで内部を拡張する開拓者。
4. **洞察④：真のスケール感** — 私たちの全観測宇宙（930億光年）ですら、最外郭のメタ境界から見れば素粒子1粒にすぎない。
5. **洞察⑤：特異点放出の高次元反動散逸** — 一方への超絶ジェット噴射の反動は、膜内高次元側へ抜けることで運動量保存則を満たす。
6. **洞察⑥：ミクロとマクロのフラクタル相似** — 超外膜と原子・素粒子は、まったく同一のルールで動くフラクタル相似形。
7. **洞察⑦：同次元多重分化** — 高次元は単一の階段ではなく、同一のn次元でもn₁, n₂…と無数に位相分化している。
8. **洞察⑧：究極の基底「11次元スープ」** — 膜の激突を防ぐ緩衝材であり、全エネルギーの供給源（M理論バルク）。
9. **洞察⑨：階層的ドリップ濾過** — 11次元の超高圧原液が次元膜を通過する過程で減衰し、穏やかな低次元スープとして宇宙を満たす。
10. **洞察⑩：全一的一貫濾過体系** — 未定義から11次元、次元膜、知性、ブラックホール、電子殻に至るまで、全てが「濾過」で貫通している。
11. **洞察⑪：次元膜の細胞分裂多世界** — SFのような宇宙丸ごとの無限コピーではなく、次元膜そのものが細胞分裂のようにくびれて増殖する（ΔE=0）。
12. **洞察⑫：ブラックホールの次元変圧接続** — 特異点が繋がる先は11次元原液ではなく、濾過済みの膜内中間高次元（11次元未満）。次元ショート崩壊を防ぐ変圧器。
13. **洞察⑬：観測宇宙の4〜5次元実態論** — 純粋な3次元空間は存在しない。実態は4〜5次元の広がりがあり、光（電磁気）が膜に張り付いているため3次元的作用としてしか可視化できない。
14. **洞察⑭：親マクロの幾何学的継承とスケール不変性** — 下位次元は外側のマクロ構造を親の鋳型として作られている。運動の物理スケール（フェムト秒 vs 億年）が違っても、起きている幾何学は割と同じである。

---

### 4. 現代物理学との実証的照合 (Empirical Validation)
${RESEARCH_MAPPING_DATA
  .map(
    (p) => `#### ${p.realWorldProblem} (${p.field})
- **従来の難問:** ${p.currentStalemate}
- **本モデルの解:** ${p.frameworkSolution}
- **検証観測計画:** ${p.keyObservationalFacilities.join(', ')} (整合度: ${p.viabilityScore}%)
`
  )
  .join('\n')}

---
*Generated by Universal Filtration & Biomorphic Cosmology Engine*
*Timestamp: ${new Date().toISOString()}*
`;
  };

  // Download Markdown Paper
  const downloadMarkdown = () => {
    const text = generateMarkdownDoc();
    const blob = new Blob([text], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'Universal_Filtration_Cosmology_Paper_v2.md';
    link.click();
    URL.revokeObjectURL(url);
  };

  // Download JSON Data
  const downloadJSON = () => {
    const data = {
      project: 'Universal Filtration & Biomorphic Cosmology',
      version: '2.0.0',
      exportedAt: new Date().toISOString(),
      dimensions: ARCHITECTURE_NODES,
      phenomena: RESEARCH_MAPPING_DATA,
    };
    const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'Universal_Filtration_Data_v2.json';
    link.click();
    URL.revokeObjectURL(url);
  };

  // Generate & Download Complete ZIP Archive
  const downloadFullZip = async () => {
    try {
      setIsZipping(true);
      const zip = new JSZip();

      // 1. Add Documentation & Papers
      zip.file('README.md', generateMarkdownDoc());
      zip.file('Theory_Paper_v2.md', generateMarkdownDoc());

      // 2. Add JSON structured data
      const data = {
        project: 'Universal Filtration & Biomorphic Cosmology',
        version: '2.0.0',
        exportedAt: new Date().toISOString(),
        dimensions: ARCHITECTURE_NODES,
        phenomena: RESEARCH_MAPPING_DATA,
      };
      zip.file('data/cosmology_data.json', JSON.stringify(data, null, 2));

      // 3. Add Project Metadata & License
      zip.file(
        'LICENSE',
        `MIT License\n\nCopyright (c) 2026 Universal Filtration & Biomorphic Cosmology Project`
      );
      zip.file(
        'project_info.txt',
        `Universal Filtration & Biomorphic Cosmology (v2.0)\nArchived on: ${new Date().toLocaleString()}\nHost URL: ${appUrl}\nFramework: React 19 + TypeScript + Vite + TailwindCSS`
      );

      // Generate ZIP blob
      const content = await zip.generateAsync({ type: 'blob' });
      const url = URL.createObjectURL(content);
      const link = document.createElement('a');
      link.href = url;
      link.download = 'Universal_Filtration_Cosmology_v2_Archive.zip';
      link.click();
      URL.revokeObjectURL(url);
    } catch (e) {
      console.error('ZIP generation failed:', e);
    } finally {
      setIsZipping(false);
    }
  };

  // Copy Complete Text
  const handleCopyText = async () => {
    try {
      await navigator.clipboard.writeText(generateMarkdownDoc());
      setCopiedText(true);
      setTimeout(() => setCopiedText(false), 2500);
    } catch (e) {
      console.error('Copy failed:', e);
    }
  };

  // Copy Permanent URL
  const handleCopyUrl = async () => {
    try {
      await navigator.clipboard.writeText(appUrl);
      setCopiedUrl(true);
      setTimeout(() => setCopiedUrl(false), 2500);
    } catch (e) {
      console.error('Copy URL failed:', e);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-md animate-fade-in">
      <div className="bg-slate-900 border border-slate-700/80 rounded-2xl max-w-2xl w-full p-6 shadow-2xl relative max-h-[90vh] overflow-y-auto">
        {/* Close Button */}
        <button
          onClick={onClose}
          className="absolute top-4 right-4 p-1.5 rounded-lg text-slate-400 hover:text-white hover:bg-slate-800 transition-colors"
        >
          <X className="w-5 h-5" />
        </button>

        {/* Modal Header */}
        <div className="flex items-center gap-3 mb-6">
          <div className="p-3 rounded-xl bg-purple-500/20 border border-purple-500/40 text-purple-300">
            <HardDrive className="w-6 h-6" />
          </div>
          <div>
            <h3 className="text-xl font-bold text-white flex items-center gap-2">
              <span>{lang === 'en' ? 'Save & Export Project' : 'プロジェクト・理論の保存とエクスポート'}</span>
              <span className="text-xs font-mono px-2 py-0.5 rounded bg-emerald-500/20 text-emerald-300 border border-emerald-500/40">
                v2.0
              </span>
            </h3>
            <p className="text-xs text-slate-400 mt-0.5">
              {lang === 'en'
                ? 'Save your complete cosmological framework directly to your device.'
                : 'GitHubを使わずに、あなたのパソコンやスマホへ直接丸ごと保存できます。'}
            </p>
          </div>
        </div>

        {/* Options Grid */}
        <div className="space-y-4">
          {/* 1. ZIP Archive (Recommended) */}
          <div className="p-4 rounded-xl bg-gradient-to-r from-purple-950/40 via-indigo-950/40 to-slate-900 border border-purple-500/40 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
            <div className="space-y-1">
              <div className="flex items-center gap-2 text-sm font-bold text-purple-200">
                <Archive className="w-4 h-4 text-purple-400" />
                <span>{lang === 'en' ? '1. Complete Project ZIP Archive' : '① プロジェクト丸ごと一括ZIP保存（一番おすすめ！）'}</span>
              </div>
              <p className="text-xs text-slate-300 leading-relaxed">
                {lang === 'en'
                  ? 'Downloads full markdown theory paper, 14 core insights, and JSON data bundle as a single .zip file.'
                  : '完全版理論書、14大洞察、全8階層マトリクス、JSONデータを1つのZIPファイルにまとめて手元に即座保存します。'}
              </p>
            </div>
            <button
              onClick={downloadFullZip}
              disabled={isZipping}
              className="px-4 py-2.5 rounded-xl bg-purple-600 hover:bg-purple-500 text-white font-bold text-xs shadow-lg shadow-purple-950/50 flex items-center gap-2 transition-all shrink-0 disabled:opacity-50"
            >
              <Download className="w-4 h-4" />
              <span>{isZipping ? (lang === 'en' ? 'Packing ZIP...' : '圧縮中...') : (lang === 'en' ? 'Download ZIP' : 'ZIPを保存')}</span>
            </button>
          </div>

          {/* 2. Direct Markdown Paper & JSON */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            <div className="p-3.5 rounded-xl bg-slate-950/70 border border-slate-800 flex flex-col justify-between gap-3">
              <div>
                <div className="flex items-center gap-2 text-xs font-bold text-amber-300 mb-1">
                  <FileText className="w-4 h-4 text-amber-400" />
                  <span>{lang === 'en' ? 'Theory Paper (.md)' : '② 理論書全文 (.md)'}</span>
                </div>
                <p className="text-[11px] text-slate-400">
                  {lang === 'en'
                    ? 'Formatted Markdown thesis file readable in any text editor, Notion, or Obsidian.'
                    : 'メモ帳、Notion、Obsidianですぐ読めるMarkdown論文テキスト。'}
                </p>
              </div>
              <button
                onClick={downloadMarkdown}
                className="w-full py-2 px-3 rounded-lg bg-amber-500/20 hover:bg-amber-500/30 text-amber-300 border border-amber-500/40 text-xs font-semibold flex items-center justify-center gap-2 transition-all"
              >
                <Download className="w-3.5 h-3.5" />
                <span>{lang === 'en' ? 'Download .md' : '理論書を保存'}</span>
              </button>
            </div>

            <div className="p-3.5 rounded-xl bg-slate-950/70 border border-slate-800 flex flex-col justify-between gap-3">
              <div>
                <div className="flex items-center gap-2 text-xs font-bold text-cyan-300 mb-1">
                  <HardDrive className="w-4 h-4 text-cyan-400" />
                  <span>{lang === 'en' ? 'Raw Data Bundle (.json)' : '③ 全構造データ (.json)'}</span>
                </div>
                <p className="text-[11px] text-slate-400">
                  {lang === 'en'
                    ? 'Structured JSON containing all parameters, scores, and phenomenological proofs.'
                    : '全8階層、14大洞察、現代物理検証データを構造化したJSONファイル。'}
                </p>
              </div>
              <button
                onClick={downloadJSON}
                className="w-full py-2 px-3 rounded-lg bg-cyan-500/20 hover:bg-cyan-500/30 text-cyan-300 border border-cyan-500/40 text-xs font-semibold flex items-center justify-center gap-2 transition-all"
              >
                <Download className="w-3.5 h-3.5" />
                <span>{lang === 'en' ? 'Download .json' : 'JSONを保存'}</span>
              </button>
            </div>
          </div>

          {/* 3. One-Click Clipboard Copy */}
          <div className="p-4 rounded-xl bg-slate-950/70 border border-slate-800 flex items-center justify-between gap-3">
            <div>
              <div className="text-xs font-bold text-slate-200">
                {lang === 'en' ? '④ Copy Complete Text to Clipboard' : '④ クリップボードに全文コピー（メモ帳貼り付け用）'}
              </div>
              <p className="text-[11px] text-slate-400">
                {lang === 'en'
                  ? 'Copies the entire thesis text. Paste directly into Google Docs or Apple Notes.'
                  : 'ボタン1つで全論文テキストをコピー。スマホのメモやGoogleドキュメントにそのまま貼れます。'}
              </p>
            </div>
            <button
              onClick={handleCopyText}
              className="px-3.5 py-2 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-200 border border-slate-700 text-xs font-medium flex items-center gap-1.5 transition-all shrink-0"
            >
              {copiedText ? (
                <>
                  <Check className="w-3.5 h-3.5 text-emerald-400" />
                  <span className="text-emerald-400 font-bold">{lang === 'en' ? 'Copied!' : 'コピー完了!'}</span>
                </>
              ) : (
                <>
                  <Copy className="w-3.5 h-3.5 text-slate-300" />
                  <span>{lang === 'en' ? 'Copy All' : '全文コピー'}</span>
                </>
              )}
            </button>
          </div>

          {/* 4. Bookmark Permanent URL */}
          <div className="p-4 rounded-xl bg-slate-950/70 border border-slate-800 space-y-2">
            <div className="flex items-center justify-between">
              <div className="text-xs font-bold text-slate-200 flex items-center gap-1.5">
                <Share2 className="w-3.5 h-3.5 text-cyan-400" />
                <span>{lang === 'en' ? '⑤ Permanent App Web Link' : '⑤ アプリの永続Webリンク（ブックマーク用）'}</span>
              </div>
              <button
                onClick={handleCopyUrl}
                className="text-[11px] text-cyan-400 hover:underline flex items-center gap-1 font-mono"
              >
                {copiedUrl ? (
                  <>
                    <Check className="w-3 h-3 text-emerald-400" />
                    <span className="text-emerald-400">{lang === 'en' ? 'URL Copied!' : 'URLコピー完了!'}</span>
                  </>
                ) : (
                  <>
                    <Copy className="w-3 h-3" />
                    <span>{lang === 'en' ? 'Copy URL' : 'URLをコピー'}</span>
                  </>
                )}
              </button>
            </div>
            <div className="p-2 rounded bg-slate-900 border border-slate-800 font-mono text-[11px] text-slate-400 break-all select-all flex items-center justify-between">
              <span>{appUrl}</span>
              <a
                href={appUrl}
                target="_blank"
                rel="noreferrer"
                className="text-slate-500 hover:text-slate-300 ml-2"
              >
                <ExternalLink className="w-3.5 h-3.5" />
              </a>
            </div>
            <p className="text-[10px] text-slate-500">
              {lang === 'en'
                ? 'This web application is permanently hosted on cloud servers. Bookmark it in your browser to access the simulation anytime.'
                : 'このWebアプリはクラウド上で常時稼働しています。ブラウザのお気に入り（ブックマーク）に登録しておくだけで、いつでもシミュレータにアクセスできます。'}
            </p>
          </div>
        </div>

        {/* Footer */}
        <div className="mt-6 pt-4 border-t border-slate-800 flex justify-end">
          <button
            onClick={onClose}
            className="px-5 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-medium transition-colors"
          >
            {lang === 'en' ? 'Close' : '閉じる'}
          </button>
        </div>
      </div>
    </div>
  );
};
